services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_NAME}', '-U', '${DB_USER}' ]
      retries: 3
      timeout: 5s
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_volume:


