name: Déploiement sur le VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main 

env:
  APP_NAME: "AUTOGO" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Configurer la clé SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Déployer sur le VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/br &&
            git pull origin main &&

            # Écrire le fichier .env
            cat > .env <<EOL
            # Google OAuth
            clientID=${{ secrets.CLIENT_ID }}
            clientSecret=${{ secrets.CLIENT_SECRET }}
            callbackURL=${{ secrets.CALLBACK_URL }}

            # Database
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}

            # Nom de l'application
            APP_NAME=${{ env.APP_NAME }}
            EOL

            npm install &&
            pm2 list | grep "${{ env.APP_NAME }}" && pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
          EOF